---
- hosts: ec2
  sudo: yes
  vars_files:
    - vars.yml
  tasks:
    - name: check if pip is installed
      shell: pip3 --version
      ignore_errors: true
      register: pip_is_installed
    
    - name: Install pip
      apt: name=python3-pip update_cache=true state=installed
      when: pip_is_installed.rc != 0

    - name: Install Dependancies
      apt: name=libapache2-mod-wsgi update_cache=true state=installed

    - name: Check If Git is Installed
      shell: git --version
      ignore_errors: true
      register: git_is_installed

    - name: Install git
      apt: name=git update_cache=true state=installed

    - name: Clone Git Repo
      git: repo={{project_repo}} dest={{install_root}} accept_hostkey=yes

    - name: Install Requirements
      pip: requirements="{{install_root}}/{{project_name}}/requirements.txt"

    - name: Copy configurations
      command: cp {{ item.src }}  {{ item.dest }}
      with_items:
        - "{{ configuration_files }}" 

    - name: Setting up environment variables
      shell: export PATH={{pythonpath}}
 
    - name: Migrate the Django App
      django_manage: command=migrate app_path={{install_root}}/{{project_name}}/{{project_name}} pythonpath={{pythonpath}}

    - name: collect static files
      django_manage: command=collectstatic app_path={{install_root}}/{{project_name}}/{{project_name}} pythonpath={{pythonpath}}

    - name: restart Apache
      service: name=apache2 state=restarted
    
