---

- hosts: localhost
  connection: local
  become: False
  gather_facts: False

  tasks:
    
    - name: Setting Up Security Group
      ec2_group:
         name: abhishek_us_east_grp
         description: Setting rules to allow traffic on 22 and 80
         region: us-east-2
         rules: 
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
  
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
         region: us-east-2
         keypair: abhishek-ohio
         instance_type: t2.micro
         image: ami-618fab04
         wait: true
         exact_count: 1
         count_tag:
            Name: Abhi_US_East
         instance_tags:
            Name: Abhi_US_East
         vpc_subnet_id: subnet-dca850a7
         assign_public_ip: yes
         group: abhishek_us_east_grp
      register: ec2


    - name: Wait for SSh to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2.instances }}'
