---
- hosts: ec2
  sudo: yes
  tasks:
    - name: Install apache2 server
      apt: name=apache2 update_cache=yes state=latest 
      notify:
        - restart apache2
        - check apache2
  handlers:
    - name: check apache2
      service: name=apache2 state=started

    - name: restart apache2
      service: name=apache2 state=restarted
